# Generated by Django 4.0.10 on 2026-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id_culture', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'culture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id_diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('date_diagnostic', models.DateTimeField()),
                ('url_image', models.CharField(blank=True, max_length=500, null=True)),
                ('description_symptomes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'diagnostic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('id_exploitation', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'exploitation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id_maladie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description_maladie', models.TextField(blank=True, null=True)),
                ('symptomes', models.TextField(blank=True, null=True)),
                ('gravite', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'maladie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id_marche', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'marche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id_parcelle', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_plantation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parcelle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrevisionMeteo',
            fields=[
                ('id_prevision', models.AutoField(primary_key=True, serialize=False)),
                ('date_prevision', models.DateField()),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('probabilite_pluie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantite_pluie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'prevision_meteo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id_prix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(max_length=50)),
                ('devise', models.CharField(max_length=10)),
                ('date_releve', models.DateField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'prix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id_recommandation', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('niveau_urgence', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'recommandation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatDiagnostic',
            fields=[
                ('id_resultat', models.AutoField(primary_key=True, serialize=False)),
                ('score_confiance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rang', models.PositiveSmallIntegerField()),
                ('est_retenu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'resultat_diagnostic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=30)),
                ('date_inscription', models.DateTimeField()),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneMeteo',
            fields=[
                ('id_zone', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'zone_meteo',
                'managed': False,
            },
        ),
    ]
